SELECT 
parent_guardian_info_aid
,parent_guardian_info_aid /* is active */
,parent_guardian_info_email
,parent_guardian_info_fname
,parent_guardian_info_lname
,financial_info_father_income
,financial_info_mother_income
,financial_info_financier_full_name
,financial_info_financier_relationship
,financial_info_financier_occupation
,financial_info_financier_income
,parent_guardian_info_created
,parent_guardian_info_datetime
FROM 
dbpzz0guc0yztg.fca_parent_guardian_info as parent
,dbpzz0guc0yztg.fca_financial_info as financial 
where
parent_guardian_info_user_id = financial_info_user_id;
