SELECT 
settings_users_aid
,settings_users_aid /* is active */
,settings_users_email
,settings_users_fname
,settings_users_lname
,financial_info_father_income
,financial_info_mother_income
,financial_info_financier_full_name
,financial_info_financier_relationship
,financial_info_financier_occupation
,financial_info_financier_income
,settings_users_created
,settings_users_datetime
FROM 
dbpzz0guc0yztg.fca_financial_info as financial
,dbpzz0guc0yztg.fca_settings_users 
where
financial_info_user_id = settings_users_aid
